const defaultSkillPool = [
	// Core Professional Skills
	"Communication",
	"Problem-Solving",
	"Adaptability",
	"Collaboration",
	"Time Management",
	"Creativity",
	"Leadership",
	"Critical Thinking",
	"Attention to Detail",
	"Decision Making",
	"Emotional Intelligence",
	"Flexibility",
	"Innovation",
	"Public Speaking",
	"Negotiation",
	"Conflict Resolution",
	"Active Listening",
	"Strategic Thinking",
	"Work Ethic",
	"Resilience",

	// Workplace & Productivity Skills
	"Organization",
	"Multitasking",
	"Self-Motivation",
	"Initiative",
	"Dependability",
	"Professionalism",
	"Accountability",
	"Collaboration",
	"Interpersonal Skills",
	"Teamwork",
	"Resourcefulness",
	"Customer Focus",
	"Relationship Building",
	"Stress Management",
	"Analytical Thinking",
	"Persuasion",
	"Decision-Making",
	"Adaptability to Change",
	"Self-Improvement",
	"Continuous Learning",
]

module.exports = defaultSkillPool
