const SERVER_RESPONSE_MESSAGES = {
	PLAN_EXPIRED: "PLAN_EXPIRED",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	YOU_USED_ALL_DOWNLOADS_UPGRADE: "YOU_USED_ALL_DOWNLOADS_UPGRADE",
	YOU_USED_YOUR_DOWNLOAD_LIMIT: "YOU_USED_YOUR_DOWNLOAD_LIMIT",
	DOWNLOAD_LIMIT_REACHED: "DOWNLOAD_LIMIT_REACHED",
	DOWNLOAD_ALLOWED: "DOWNLOAD_ALLOWED",
	AUTH_ERROR: "AUTH_ERROR",
	SERVER_ERROR: "SERVER_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
	PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
	DOWNLOADS_REMAINING: "DOWNLOADS_REMAINING",
	PLAN_CHANGE_TO_FREE_SUCCESS: "PLAN_CHANGE_TO_FREE_SUCCESS",
}

module.exports = SERVER_RESPONSE_MESSAGES

if (typeof module !== "undefined" && module.exports) {
	module.exports = SERVER_RESPONSE_MESSAGES
	module.exports.default = SERVER_RESPONSE_MESSAGES
	module.exports.SERVER_RESPONSE_MESSAGES = SERVER_RESPONSE_MESSAGES
}
